package entidades;
// Generated 11/08/2016 23:28:16 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="roquedb"
)
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Fornecedor fornecedor;
     private Produto produto;
     private Usuario usuario;
     private int quantidade;
     private float custoUnit;
     private Date data;

    public Compra() {
    }

    public Compra(Fornecedor fornecedor, Produto produto, Usuario usuario, int quantidade, float custoUnit, Date data) {
       this.fornecedor = fornecedor;
       this.produto = produto;
       this.usuario = usuario;
       this.quantidade = quantidade;
       this.custoUnit = custoUnit;
       this.data = data;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_compra", unique=true, nullable=false)
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_fornecedor", nullable=false)
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_produto", nullable=false)
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="quantidade", nullable=false)
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="custo_unit", nullable=false, precision=12, scale=0)
    public float getCustoUnit() {
        return this.custoUnit;
    }
    
    public void setCustoUnit(float custoUnit) {
        this.custoUnit = custoUnit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


