package entidades;
// Generated 11/08/2016 23:28:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,catalog="roquedb"
)
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Cliente cliente;
     private Usuario usuario;
     private Date data;
     private float valorTotal;
     private Set itensPedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, Usuario usuario, Date data, float valorTotal) {
        this.cliente = cliente;
        this.usuario = usuario;
        this.data = data;
        this.valorTotal = valorTotal;
    }
    public Pedido(Cliente cliente, Usuario usuario, Date data, float valorTotal, Set itensPedidos) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.data = data;
       this.valorTotal = valorTotal;
       this.itensPedidos = itensPedidos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_pedido", unique=true, nullable=false)
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", nullable=false, length=10)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="valor_total", nullable=false, precision=12, scale=0)
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pedido")
    public Set getItensPedidos() {
        return this.itensPedidos;
    }
    
    public void setItensPedidos(Set itensPedidos) {
        this.itensPedidos = itensPedidos;
    }




}


