package entidades;
// Generated 11/08/2016 23:28:16 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "roquedb"
)
public class Usuario implements java.io.Serializable {

    private Integer idUsuario;
    private Cargo cargo;
    private String nome;
    private String login;
    private String senha;
    private String campoPesquisa;
    private Set compras = new HashSet(0);
    private Set pedidos = new HashSet(0);

    public Usuario() {
    }

    public Usuario(Cargo cargo, String nome) {
        this.cargo = cargo;
        this.nome = nome;
        
    }

    public Usuario(Cargo cargo, String nome, String login, String senha, Set compras, Set pedidos) {
        this.cargo = cargo;
        this.nome = nome;
        this.login = login;
        this.senha = senha;
        this.compras = compras;
        this.pedidos = pedidos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_usuario", unique = true, nullable = false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cargo", nullable = false)
    public Cargo getCargo() {
        return this.cargo;
    }

    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

    @Column(name = "nome", nullable = false, length = 150)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }


    @Column(name = "login", length = 25)
    public String getLogin() {
        return this.login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    @Column(name = "senha", length = 25)
    public String getSenha() {
        return this.senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set getCompras() {
        return this.compras;
    }

    public void setCompras(Set compras) {
        this.compras = compras;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set getPedidos() {
        return this.pedidos;
    }

    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

    public void setCampoPesquisaUsuario(String campoPesquisaUsuario) {
        this.campoPesquisa = campoPesquisaUsuario;
    }

    public String getCampoPesquisaUsuario() {
        return campoPesquisa;
    }

    @Override
    public String toString() {
        return getNome();
    }

}
