/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author giacomin
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1PRINCIPAL = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemArquivoSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        itemCadastroCidade = new javax.swing.JMenuItem();
        ItemCadastroCliente = new javax.swing.JMenuItem();
        itemCadastroFornecedor = new javax.swing.JMenuItem();
        itemCadastroProduto = new javax.swing.JMenuItem();
        itemCadastroCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roquerou");

        jDesktopPane1PRINCIPAL.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane1PRINCIPAL.setName("Roquerou"); // NOI18N
        jDesktopPane1PRINCIPAL.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1PRINCIPALLayout = new javax.swing.GroupLayout(jDesktopPane1PRINCIPAL);
        jDesktopPane1PRINCIPAL.setLayout(jDesktopPane1PRINCIPALLayout);
        jDesktopPane1PRINCIPALLayout.setHorizontalGroup(
            jDesktopPane1PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1PRINCIPALLayout.setVerticalGroup(
            jDesktopPane1PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");
        menuArquivo.setToolTipText("");

        itemArquivoSair.setText("Sair");
        itemArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemArquivoSair);

        menuPrincipal.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        itemCadastroCidade.setText("Cidade");
        itemCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroCidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroCidade);

        ItemCadastroCliente.setText("Cliente");
        ItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(ItemCadastroCliente);

        itemCadastroFornecedor.setText("Fornecedor");
        itemCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroFornecedorActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroFornecedor);

        itemCadastroProduto.setText("Produto");
        itemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroProduto);

        itemCadastroCompra.setText("Compra");
        itemCadastroCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroCompraActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroCompra);

        menuPrincipal.add(menuCadastro);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroCidadeActionPerformed
        TelaCidade telaCidade = new TelaCidade();
        telaCidade.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCidade);
        telaCidade.moveToFront();

    }//GEN-LAST:event_itemCadastroCidadeActionPerformed

    private void itemArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArquivoSairActionPerformed
        dispose();
    }//GEN-LAST:event_itemArquivoSairActionPerformed

    private void ItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCadastroClienteActionPerformed

        TelaCliente telaCliente = new TelaCliente();
        telaCliente.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCliente);
        telaCliente.moveToFront();

// TODO add your handling code here:
    }//GEN-LAST:event_ItemCadastroClienteActionPerformed

    private void itemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroProdutoActionPerformed
        TelaProduto telaProduto = new TelaProduto();
        telaProduto.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaProduto);
        telaProduto.moveToFront();
    }//GEN-LAST:event_itemCadastroProdutoActionPerformed

    private void itemCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroFornecedorActionPerformed

        TelaFornecedor telaFornecedor = new TelaFornecedor();
        telaFornecedor.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaFornecedor);
        telaFornecedor.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCadastroFornecedorActionPerformed

    private void itemCadastroCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroCompraActionPerformed
        TelaCompra telaCompra = new TelaCompra();
        telaCompra.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCompra);
        telaCompra.moveToFront();
    }//GEN-LAST:event_itemCadastroCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCadastroCliente;
    private javax.swing.JMenuItem itemArquivoSair;
    private javax.swing.JMenuItem itemCadastroCidade;
    private javax.swing.JMenuItem itemCadastroCompra;
    private javax.swing.JMenuItem itemCadastroFornecedor;
    private javax.swing.JMenuItem itemCadastroProduto;
    private javax.swing.JDesktopPane jDesktopPane1PRINCIPAL;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
