/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import chat.Clientechat;
import dao.NivelDAO;
import entidades.Usuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author giacomin
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1PRINCIPAL = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jbUsuarios = new javax.swing.JButton();
        jbFornecedores = new javax.swing.JButton();
        jbFornecedores1 = new javax.swing.JButton();
        jbFornecedores2 = new javax.swing.JButton();
        jbchat = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemArquivoSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        itemCadastroCidade = new javax.swing.JMenuItem();
        ItemCadastroCliente = new javax.swing.JMenuItem();
        itemCadastroFornecedor = new javax.swing.JMenuItem();
        itemCadastroProduto = new javax.swing.JMenuItem();
        itemCadastroCompra = new javax.swing.JMenuItem();
        itemCadastroUsuario = new javax.swing.JMenuItem();
        itemCadastroVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Roquerou");

        jDesktopPane1PRINCIPAL.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane1PRINCIPAL.setName("Roquerou"); // NOI18N
        jDesktopPane1PRINCIPAL.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopPane1PRINCIPALLayout = new javax.swing.GroupLayout(jDesktopPane1PRINCIPAL);
        jDesktopPane1PRINCIPAL.setLayout(jDesktopPane1PRINCIPALLayout);
        jDesktopPane1PRINCIPALLayout.setHorizontalGroup(
            jDesktopPane1PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1PRINCIPALLayout.setVerticalGroup(
            jDesktopPane1PRINCIPALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/People.png"))); // NOI18N
        jButton1.setText("Clientes");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDisabledIcon(null);
        jButton1.setDisabledSelectedIcon(null);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMaximumSize(new java.awt.Dimension(75, 55));
        jButton1.setMinimumSize(new java.awt.Dimension(75, 55));
        jButton1.setPreferredSize(new java.awt.Dimension(75, 55));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jbUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jbUsuarios.setText("Usuarios");
        jbUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbUsuarios.setFocusable(false);
        jbUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbUsuarios.setMaximumSize(new java.awt.Dimension(75, 55));
        jbUsuarios.setMinimumSize(new java.awt.Dimension(75, 55));
        jbUsuarios.setPreferredSize(new java.awt.Dimension(75, 55));
        jbUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuariosActionPerformed(evt);
            }
        });
        jToolBar2.add(jbUsuarios);

        jbFornecedores.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jbFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Boss.png"))); // NOI18N
        jbFornecedores.setText("Fornecedores");
        jbFornecedores.setToolTipText("Fornecedores");
        jbFornecedores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFornecedores.setDisabledIcon(null);
        jbFornecedores.setDisabledSelectedIcon(null);
        jbFornecedores.setFocusable(false);
        jbFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbFornecedores.setMaximumSize(new java.awt.Dimension(75, 55));
        jbFornecedores.setMinimumSize(new java.awt.Dimension(75, 55));
        jbFornecedores.setPreferredSize(new java.awt.Dimension(75, 55));
        jbFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornecedoresActionPerformed(evt);
            }
        });
        jToolBar2.add(jbFornecedores);

        jbFornecedores1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jbFornecedores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos2.png"))); // NOI18N
        jbFornecedores1.setText("Produtos");
        jbFornecedores1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbFornecedores1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFornecedores1.setFocusable(false);
        jbFornecedores1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbFornecedores1.setMaximumSize(new java.awt.Dimension(75, 55));
        jbFornecedores1.setMinimumSize(new java.awt.Dimension(75, 55));
        jbFornecedores1.setPreferredSize(new java.awt.Dimension(75, 55));
        jbFornecedores1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbFornecedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornecedores1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jbFornecedores1);

        jbFornecedores2.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jbFornecedores2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shop-cart-icon.png"))); // NOI18N
        jbFornecedores2.setText("Compra");
        jbFornecedores2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbFornecedores2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbFornecedores2.setFocusable(false);
        jbFornecedores2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbFornecedores2.setMaximumSize(new java.awt.Dimension(75, 55));
        jbFornecedores2.setMinimumSize(new java.awt.Dimension(75, 55));
        jbFornecedores2.setPreferredSize(new java.awt.Dimension(75, 55));
        jbFornecedores2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbFornecedores2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFornecedores2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jbFornecedores2);

        jbchat.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jbchat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/7140_32x32.png"))); // NOI18N
        jbchat.setText("Chat");
        jbchat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbchat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbchat.setFocusable(false);
        jbchat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbchat.setMaximumSize(new java.awt.Dimension(75, 55));
        jbchat.setMinimumSize(new java.awt.Dimension(75, 55));
        jbchat.setPreferredSize(new java.awt.Dimension(75, 55));
        jbchat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbchat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbchatActionPerformed(evt);
            }
        });
        jToolBar2.add(jbchat);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Close.png"))); // NOI18N
        jButton3.setText("Sair");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setDisabledIcon(null);
        jButton3.setDisabledSelectedIcon(null);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(75, 55));
        jButton3.setMinimumSize(new java.awt.Dimension(75, 55));
        jButton3.setPreferredSize(new java.awt.Dimension(75, 55));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton3);

        menuArquivo.setText("Arquivo");
        menuArquivo.setToolTipText("");

        itemArquivoSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        itemArquivoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Close.png"))); // NOI18N
        itemArquivoSair.setText("Sair");
        itemArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemArquivoSair);

        menuPrincipal.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        itemCadastroCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cidade.png"))); // NOI18N
        itemCadastroCidade.setText("Cidade");
        itemCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroCidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroCidade);

        ItemCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/People.png"))); // NOI18N
        ItemCadastroCliente.setText("Cliente");
        ItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(ItemCadastroCliente);

        itemCadastroFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Boss.png"))); // NOI18N
        itemCadastroFornecedor.setText("Fornecedor");
        itemCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroFornecedorActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroFornecedor);

        itemCadastroProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos2.png"))); // NOI18N
        itemCadastroProduto.setText("Produto");
        itemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroProduto);

        itemCadastroCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shop-cart-icon.png"))); // NOI18N
        itemCadastroCompra.setText("Compra");
        itemCadastroCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroCompraActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroCompra);

        itemCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        itemCadastroUsuario.setText("Usuario");
        itemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroUsuario);

        itemCadastroVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Accounting.png"))); // NOI18N
        itemCadastroVenda.setText("Venda");
        itemCadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroVendaActionPerformed(evt);
            }
        });
        menuCadastro.add(itemCadastroVenda);

        menuPrincipal.add(menuCadastro);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1PRINCIPAL, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroCidadeActionPerformed
        TelaCidade telaCidade = new TelaCidade();
        telaCidade.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCidade);
        telaCidade.moveToFront();

    }//GEN-LAST:event_itemCadastroCidadeActionPerformed

    private void itemArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArquivoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemArquivoSairActionPerformed

    private void ItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCadastroClienteActionPerformed

        TelaCliente telaCliente = new TelaCliente();
        telaCliente.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCliente);
        telaCliente.moveToFront();
    }//GEN-LAST:event_ItemCadastroClienteActionPerformed

    private void itemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroProdutoActionPerformed
        TelaProduto telaProduto = new TelaProduto();
        telaProduto.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaProduto);
        telaProduto.moveToFront();
    }//GEN-LAST:event_itemCadastroProdutoActionPerformed

    private void itemCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroFornecedorActionPerformed
        TelaFornecedor telaFornecedor = new TelaFornecedor();
        telaFornecedor.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaFornecedor);
        telaFornecedor.moveToFront();
    }//GEN-LAST:event_itemCadastroFornecedorActionPerformed

    private void itemCadastroCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroCompraActionPerformed
        TelaCompra telaCompra = new TelaCompra();
        telaCompra.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCompra);
        telaCompra.moveToFront();
    }//GEN-LAST:event_itemCadastroCompraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        TelaCliente telaCliente = new TelaCliente();
        telaCliente.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCliente);
        telaCliente.moveToFront();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornecedoresActionPerformed
        TelaFornecedor telaFornecedor = new TelaFornecedor();
        telaFornecedor.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaFornecedor);
        telaFornecedor.moveToFront();
    }//GEN-LAST:event_jbFornecedoresActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void itemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroUsuarioActionPerformed

        TelaUsuario telaUsuario = new TelaUsuario();
        telaUsuario.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaUsuario);
        telaUsuario.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCadastroUsuarioActionPerformed

    private void jbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuariosActionPerformed

        TelaUsuario telaUsuario = new TelaUsuario();
        telaUsuario.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaUsuario);
        telaUsuario.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbUsuariosActionPerformed

    private void jbFornecedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornecedores1ActionPerformed

        TelaProduto telaProduto = new TelaProduto();
        telaProduto.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaProduto);
        telaProduto.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFornecedores1ActionPerformed

    private void jbFornecedores2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFornecedores2ActionPerformed

        TelaCompra telaCompra = new TelaCompra();
        telaCompra.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaCompra);
        telaCompra.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFornecedores2ActionPerformed

    private void itemCadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroVendaActionPerformed

        TelaItens telaItens = new TelaItens();
        telaItens.setVisible(true);
        jDesktopPane1PRINCIPAL.add(telaItens);
        telaItens.moveToFront();
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCadastroVendaActionPerformed

    private void jbchatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbchatActionPerformed

        try {
            TelaChat tc = new TelaChat();
            tc.setVisible(true);
            jDesktopPane1PRINCIPAL.add(tc);
            tc.moveToFront();

            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbchatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCadastroCliente;
    private javax.swing.JMenuItem itemArquivoSair;
    private javax.swing.JMenuItem itemCadastroCidade;
    private javax.swing.JMenuItem itemCadastroCompra;
    private javax.swing.JMenuItem itemCadastroFornecedor;
    private javax.swing.JMenuItem itemCadastroProduto;
    private javax.swing.JMenuItem itemCadastroUsuario;
    private javax.swing.JMenuItem itemCadastroVenda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    public static javax.swing.JDesktopPane jDesktopPane1PRINCIPAL;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jbFornecedores;
    private javax.swing.JButton jbFornecedores1;
    private javax.swing.JButton jbFornecedores2;
    private javax.swing.JButton jbUsuarios;
    private javax.swing.JButton jbchat;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
